### ISSUE TITLE
<C-Space> not working for autocomplete popup

### ISSUE THREAD

**Issue by belkevich** [Shougo/neocomplcache.vim#329]
Using
`inoremap <expr><C-Space> pumvisible() ? "\<C-Space>" : "\<C-n>"`
I got error:
`"No inserted text yet"`

But it works fine for <Tab>
`inoremap <expr><Tab> pumvisible() ? "\<Tab>" : "\<C-n>"`

Any ideas?

**Comment by theholy7** [comment]
@Shougo I know I am super late to this thread, but can you explain why it is @ and not space? I can't find a reason for it, and I don't understand...

**Comment by Shougo** [comment]
If you use `<C-Space>` in terminal, terminal send `<C-@>` code.
Because `<C-Space>` code does not exist in TUI application.
`<C-@>` is used instead.
It is terminal behavior.  Not Vim.
So you need to map `<C-@>` instead.
