### ISSUE TITLE
Maybe this is why the candidate menu flick

### ISSUE THREAD

**Issue by UncleBill** [Shougo/neocomplcache.vim#426]
I set

``` viml
let g:neocomplcache_enable_auto_select = 1
```

But the odd selecting behavior:

1.First, I type `he`, and the menu pops up
# ![Imgur](http://i.imgur.com/f5qHUcA.jpg)

2.automaticly select the 1st match
# ![Imgur](http://i.imgur.com/X8F6FXI.png)

3.then, "head" becomes "he" again ( update)
![Imgur](http://i.imgur.com/f5qHUcA.jpg)

---

3 steps make it flick

**Comment by Shougo** [comment]
The patch is already todo listed in long time...
