### ISSUE TITLE
neocomplecache will change external completeopt vaule

### ISSUE THREAD

**Issue by ysheng26** [Shougo/neocomplcache.vim#453]
I wrote `set completeopt=longest,menu` in my `.vimrc`

but as soon as neocomplcache works, completeopt's value will be changed by:
  `set completeopt-=menu`
  `set completeopt-=longest`
  `set completeopt+=menuone`
which is located in `autoload/neocomplcache/handler.vim` `Line182`

And I really do miss the `longest` option:)

**Comment by kawing-chiu** [comment]
But I need the "longest" option when using omni complete (I mean when neocomplete refer to some omni complete backend)?

**Comment by Shougo** [comment]
Nothing.
I don't recommend to use it.

**Comment by kawing-chiu** [comment]
In my case, it's vim-clang and I've figured out how to do it: vim-clang provides options `g:clang_cpp_completeopt` and `g:clang_c_completeopt`. Just set it there. So it seems that it's the job of the omni-completion provider to support it.
