### ISSUE TITLE
Only map <c-p> and <c-n> while the neocomplcache menu is active

### ISSUE THREAD

**Issue by chilicuil** [Shougo/neocomplcache.vim#498]
Hi,

First of all, thank you for the great work on this plugin, I wonder if there is a way to make `<c-p>` and `<c-n>` behave in the way neocomplcache wants only when a completion menu is displayed. This is because I think `<c-p>` / `<c-n>` have too many possibilities to stay only linked to neocomplcache. My current use case is to map `<c-p>` to `pastetoggle` but still be able to use it when neocomplcache shows me an autocompletion menu.

If it's not possible I'll sacrifice both keymaps since I really like neocomplcache but anyway I was wondering.

Best regards.

**Comment by Shougo** [comment]
Thanks.  But it is not possible.
Because, it is overwritted in Vim.  You cannot remap it in completion window.
You can request the feature in vim_dev.
