### ISSUE TITLE
neocomplcache with coffeescript

### ISSUE THREAD

**Issue by cvlmtg** [Shougo/neocomplcache.vim#499]
I've a problem with coffeescript. let's suppose I write this object

````
object =
  foo: ->
    console.log 'foo'
  bar: ->
    |
````

If I write ```@f``` and I start autocomplete, I'd like to complete to ```@foo``` but instead it does complete to nothing. is there a way to tell neocomplcache to ignore ```@``` and complete "foo"?

**Comment by Shougo** [comment]
You must change `g:neocomplcache_keyword_patterns` value.

**Comment by cvlmtg** [comment]
I've tried but it doesn't work:

````
if !exists('g:neocomplcache_keyword_patterns')
   let g:neocomplcache_keyword_patterns = {}
endif
let g:neocomplcache_keyword_patterns.coffee = '@\w*'
```

**Comment by cvlmtg** [comment]
I also tried '[@\h]\w*' and '@\?\h\w*'
