### ISSUE TITLE
Method to collect results from omnifunc without selecting first result

### ISSUE THREAD

**Issue by expipiplus1** [Shougo/neocomplcache.vim#500]
For example I type the beginning of an identifier and NeoComplete hasn't found a match so I hit <C-x><C-o> to call the omnifunc. The ideal behavior here would be for NeoComplete to add the results from omnifunc to its list and allow me to select from them as I like (for example fuzzy matching or smart case). Here <C-x><C-o> could be any keypress, that's not important.
At the moment what happens is omnifunc takes over and none of the NeoComplete settings seem to be in effect.
Occasionally I'm able to get the completion list populated properly, but this is a little sporadic.

Hopefully there's already a way to do this.

**Comment by Shougo** [comment]
It is neocomplete issue.  It is not neocomplcache.vim issue.

**Comment by expipiplus1** [comment]
Oops!
See Shougo/Neocomplete#374
