### ISSUE TITLE
filename_include source not working in Neovim

### ISSUE THREAD

**Issue by ajpaulson** [Shougo/neocomplcache.vim#502]
I am using neocomplcache in neovim (it's the best autocomplete option for Neovim) with your recommended config settings.

When I write a C or CPP file no suggestions for header files are suggested.

example:
   `#include <std`

There are no [FI] suggestions (stdio.h for instance) only 2 [S] suggestions.

I have vimproc installed to automatically build cache.

Is this a known issue? 
(System: Debian Jessie)

**Comment by Shougo** [comment]
Please check your 'path' configuration.
I think it does be not set properly.

**Comment by ajpaulson** [comment]
The path is set correctly and if I use neocomplete in regular vim it suggests [FI] completions.

My compilers also find header files.

**Comment by Shougo** [comment]
Fixed it.

**Comment by ajpaulson** [comment]
Thank you, it works perfectly now.
