### ISSUE TITLE
Can remove completefunc in neocomplcache?

### ISSUE THREAD

**Issue by xHN35RQ** [Shougo/neocomplcache.vim#503]
I noticed you removed completefunc in neocomplete: https://github.com/Shougo/neocomplete.vim/issues/315

Can this be done in neocomplcache? Because I'm using neovim and it has no lua support, so I use neocomplcache and it gives conflict with plugins that set their own complete function.

**Comment by Shougo** [comment]
No.  Because, neocomplcache development is already finished.

For neovim, I will develop new completion plugin.
https://github.com/Shougo/deoplete.nvim

It does not use completefunc anymore.

**Comment by xHN35RQ** [comment]
Thanks!!
