### ISSUE TITLE
NeoComplCache

### ISSUE THREAD

**Issue by shiro-saber** [Shougo/neocomplcache.vim#505]
Hi
it is not an issue as such, my question, I read that you can use neocomplcache with clang complete to have an autocomplete for c ++, Could you say if it is true ?, if that's true, how this would be done?

**Comment by Shougo** [comment]
```vim
	let g:clang_complete_auto = 0
	let g:clang_auto_select = 0
	let g:clang_default_keymappings = 0
	"let g:clang_use_library = 1
```

And please set `g:neocomplcache_force_omni_patterns`.
