### ISSUE TITLE
Undefined function pythoncomplete#Complete

### ISSUE THREAD

**Issue by xzwj** [Shougo/neocomplcache.vim#509]
when I use ".\<tab>", I got an error: 
function neocomplcache#handler #_do_auto_complete[55] .. neocomplcache#complete#set_results_pos[32] ..437[8]..<SNR>193_set_complete_results_pos
function neocomplcache#handler #_do_auto_complete[55]..neocomplcache#complete#set_Vim(let):E117:
undefined function:pythoncomplete#Complete

I check `:echo has('python')` returns 0 and `setl omnifunc` returns omnifunc=pythoncomplete#Complete, but `:echo has('python3')` returns 1

I usually use vim edit python3, and occasionally edit python2.  how can I fix it?

**Comment by Shougo** [comment]
In Python3 only environment, `setlocal omnifunc=python3complete#Complete` is needed.

> I usually use vim edit python3, and occasionally edit python2. how can I fix it?

You should use Python3 complete instead.

**Comment by xzwj** [comment]
Hey, Shougo. I have added `autocmd FileType python setlocal omnifunc=pythoncomplete#Complete` in .vimrc. but it have no effect. I have just started learning vim. could you tell me more detailed? Thank you!

**Comment by Shougo** [comment]
Oh, I had mistake.

```vim
autocmd FileType python setlocal omnifunc=python3complete#Complete
```

**Comment by xzwj** [comment]
Fixed! Thank you again :)
